language: java

jdk:
 - oraclejdk9
 - oraclejdk8

sudo: true

before_script: 
  - "wget -O - https://github.com/jphp-compiler/jphp/releases/download/jppm-0.4.0/jppm-setup-0.4.0.sh | sudo bash"
  
script: 
  - "jppm publish --yes"
